version: '3'

# Competition, development on iMac, builds PicInch in container, test without HTTPS

services:

  db:
    image: mariadb:10.4
    container_name: picinch_db
    expose:
      - 3306
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root-test-only
      MYSQL_DATABASE: picinch
      MYSQL_USER: server
      MYSQL_PASSWORD: test-only
    volumes:
      - ./mysql-competition:/var/lib/mysql
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
      
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 9080:8080

  server:
    build: app/.
    ports:
      - 8000:8000
    restart: unless-stopped
    environment:
      domains: ""
      db-source: tcp(picinch_db:3306)/picinch
      db-password: test-only
      admin-name: admin@picinch.com
      admin-password: admin-test-only
      home-switch: standby
      options: main-comp
    volumes:
      - ./photos:/photos
      - ~/Websites/rotarypetshow/srv/picinch/site:/site
      - ./misc:/misc
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
        max-file: "10"
    depends_on:
      - db