---
# Configuration for PicInch Gallery server
#  - Edit and rename to configuration.yml
#  - Take care to keep indentation unchanged when editing. Do not use tabs.

db-password: test-only

admin-name: admin@example.com
admin-password: admin-test-only

# Website mode
options: <club|solo|main-comp>

# The following is needed for certificate registration with Let's Encrypt
domains:
  - example.com
  - www.example.com

# Address to be notified of problems with certificates
certificate-email: you@example.com

# Administrator, to be added to the database
admin-name: admin@example.com
admin-password: <your-password>